version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: nginx-data
        target: /usr/share/nginx/html

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

volumes:
  nginx-data:
  mysql-data:

