# Sử dụng hình ảnh Nginx chính thức từ Docker Hub
FROM nginx:latest

# Expose port 80 để có thể truy cập web server
EXPOSE 80

# Lệnh để khởi động Nginx khi container chạy
CMD ["nginx", "-g", "daemon off;"]
